### PR TITLE
modulesync 4.1.0

### PR DESCRIPTION
**Pull request by bastelfreak**
modulesync 4.0.0

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
Not sure why the unit tests are failing. Debian 10 is expected since there are no Puppetserver 5 packages (they never existed).

**Comment by towo** [comment]
FWIW, this is currently *at least* blocked by a missing new release of voxpupuli/puppet-python, since voxpupuli/puppet-python#587 is a blocker for the unit tests.

**Comment by kenyon** [comment]
Just rebased on current master to see how the tests go now.

**Comment by kenyon** [comment]
Needs https://github.com/puppetlabs/puppetlabs-puppetdb/pull/327 and a new release of puppetlabs-puppetdb containing that.

**Comment by bastelfreak** [comment]
* pinged Puppet again about a puppetlabs-puppetdb release
* run modulesync 4.1.0
* allow vcsrepo 4.x

**Comment by smortex** [comment]
A new puppetlabs-puppetdb has been released…  Will it help?

**Comment by smortex** [comment]
An image showing somebody happy

The test suite is green! :green_heart: :green_heart: :green_heart:

**Review by ekohl — APPROVED** [review]

**Pull request merged**
