### PR TITLE
change python provider to puppet/python

### LINKED ISSUE #215: stankevich-python has been deprecated
It's very recent, but the stankevich-python entry is puppet forge has this message:

```
This module has been deprecated by its author since June 27, 2018.
The reason given was:
This module has been adopted by Vox Populi.
The author has suggested puppet-python as its replacement.
```

I have made this replacement in my puppet file and the (limited) code I have still seems to work.

### PR DESCRIPTION
**Pull request by mergwyn**
#### Pull Request (PR) description
stankevich/python has been deprecated. This PR replaces it with puppet/python

#### This Pull Request (PR) fixes the following issues
Fixes #215 

It's a pretty straightforward change and seems to work in my (limited) environment. I am not expert enough to be able to run unit tests.

### CODE REVIEW

**Comment by bastelfreak** [comment]
@mergwyn thanks for the PR. Can you also update the link in the .fixtures.yml? https://github.com/voxpupuli/puppet-puppetboard/blob/master/.fixtures.yml#L6

**Comment by mergwyn** [comment]
Sorry about that, I did a grep -R for * and not . duh!

**Comment by bastelfreak** [comment]
I recommend `git grep..` :)

**Comment by mattock** [comment]
@bastelfreak this is now ready to be merged, right?

**Comment by bastelfreak** [comment]
Thanks!

**Pull request merged**
