### PR TITLE
Release 11.0.0

### PR DESCRIPTION
**Pull request by d1nuc0m**
#### Pull Request (PR) description

Release 11.0.0, major version bump due to Ubuntu 18.04 support drop

### CODE REVIEW

**Review by kenyon — COMMENTED** [review]
Should we also drop support for EOL Debian 10 and FreeBSD 12 for this release?

**Comment by d1nuc0m** [comment]
> Should we also drop support for EOL Debian 10 and FreeBSD 12 for this release?

Good idea, would it be enough to remove them from `metadata.json`?

**Comment by kenyon** [comment]
Remove from `metadata.json`, and remove any code and hiera data related to them.

Also, what about #417? #396 and #412 would be good to get in too. Also #414, since that is also a breaking change.

**Comment by d1nuc0m** [comment]
> Remove from `metadata.json`, and remove any code and hiera data related to them.
> 
> Also, what about #417? #396 and #412 would be good to get in too. Also #414, since that is also a breaking change.

- #417 - I think it can be merged meanwhile
- #396 - now there are [PuppetDB packages for Debian 12](https://apt.puppet.com/pool/bookworm/puppet8/p/puppetdb/index.html), can you run the actions again? 
- #412 can you run the actions again?
- #414 would conflict with #416 , tbh as apache module is now optional I would still leave config examples, IMHO it's up to the users to config securely their own sites

**Comment by kenyon** [comment]
I merged #396, #412, and #417. Can you regenerate the changelog please?

**Comment by d1nuc0m** [comment]
@kenyon If possible, I'd wait for #419 merge, as you suggested I was able to work on dropping Debian 10 and FreeBSD 12

When it's merged I'll rebase etc

**Comment by d1nuc0m** [comment]
@kenyon done

**Pull request merged**
