### PR TITLE
#338 - Target Python 3.9 for Debian 11

### LINKED ISSUE #338: Debian 11 data targets incorrect system python version
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: v7.10.0
- Distribution: Debian (11)
- Module version: 8.0.0

## How to reproduce (e.g Puppet code you use)

```puppet
  class { 'puppetboard':
    manage_virtualenv => true,
    offline_mode      => true,
    revision          => 'v3.1.0'
  }
```

## What are you seeing

Using `puppetboard` module fails on Debian 11 as it is trying to install `python3.8-venv`.

## What behaviour did you expect instead

Puppetboard should be attempting to install the `python3.9-venv` package.

Debian 11 released with a system Python of 3.9, the module data just needs updating. 

## Output log

```
Error: /Stage[main]/Profile::Puppet::Master::Webserver/Letsencrypt::Certonly[puppetmaster]/Exec[letsencrypt certonly puppetmaster]/returns: change from 'notrun' to ['0'] failed: /bin/sh: 1: /opt/letsencrypt/.venv/bin/letsencrypt: not found
 (corrective)
Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install python3.8-venv' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package python3.8-venv
E: Couldn't find any package by glob 'python3.8-venv'
E: Couldn't find any package by regex 'python3.8-venv'
Error: /Stage[main]/Puppetboard/Python::Pyvenv[/srv/puppetboard/virtenv-puppetboard]/Package[python3.8-venv]/ensure: change from 'purged' to 'present' failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install python3.8-venv' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package python3.8-venv
E: Couldn't find any package by glob 'python3.8-venv'
E: Couldn't find any package by regex 'python3.8-venv'
```

## Any additional information you'd like to impart
Relevant Puppetfile versions:
```
mod 'puppet-puppetboard',                   '8.0.0'
mod 'puppet-python',                        '6.2.0'
```

In the meantime, end users can work around this by manually targeting the following hiera value for Debian 11 hosts:
```
puppetboard::python_version: '3.9'
```

### PR DESCRIPTION
**Pull request by dowlingw**
#### Pull Request (PR) description
Update module data to target correct system python for Debian 11.

#### This Pull Request (PR) fixes the following issues
Fixes #338

### CODE REVIEW

**Comment by smortex** [comment]
Debian 11 is not supported.  Do you mind adding it to metadata.json so that we can run the test suite against it?

**Comment by smortex** [comment]
A yes… We need the server components for Debian 11 which are not available (yet!)

Do you mind if we keep this on hold until packages are available and the whole stack can be reliably tested?

**Comment by smortex** [comment]
> hey folks, we are hoping to land this in our January release. Thanks for your patience!

[Source](https://tickets.puppetlabs.com/browse/SERVER-3096?focusedCommentId=838325&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-838325)

But no Puppet 6 package expected so this might get tricky for our CI :-/

**Comment by smortex** [comment]
Maybe we can remove Debian 11 from metadata.json for now: I realize this is actually a bugfix.

**Comment by kenyon** [comment]
Fixed in #348.

**Pull request closed without merging**
