### PR TITLE
Travis fixes

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
ping @nibalizer

**Comment by bastelfreak** [comment]
instead we should do a modulesync. this will also fix the issues. We dropped puppet-lint as a explicit dependency because the lint plugins already have it.

**Comment by ghoneycutt** [comment]
Could you please leave this open until the problem is actually fixed

**Comment by ghoneycutt** [comment]
Should I send this PR to some other repo that is the source for the modulesync?

**Pull request closed without merging**
