### PR TITLE
Updating dependencies

### LINKED ISSUE #245: Support vcsrepo v3.0.0
Allow puppetlabs/vcsrepo v3.0.0

https://github.com/puppetlabs/puppetlabs-vcsrepo/blob/master/CHANGELOG.md

### PR DESCRIPTION
**Pull request by pjonesIDBS**
Successfully tested with these versions locally. They are the current latest versions.

### CODE REVIEW

**Comment by pjonesIDBS** [comment]
Sadly, this change is currently blocked by https://github.com/voxpupuli/pypuppetdb/issues/158 as there's missing dependencies for the pypuppetdb module. It appears these were introduced in v1.0.0 of the pypuppetdb module.

I've confirmed that if I set pypuppetdb ==0.3.3 in requirements.txt (local equivalent to https://github.com/voxpupuli/puppetboard/blob/master/requirements.txt) then Puppet runs through correctly. Hopefully this will solve most of the build failures. 

@bastelfreak, how would you prefer to move this forward? Are you okay to either add the missing requirements file to pypuppetdb and nudge the version on, or else version lock pypuppetdb in the requirements.txt for the puppetboard repo?

**Comment by bastelfreak** [comment]
I think it shouldn't be too hard to fix this in pypuppetdb. We can kick of a new release afterwards.

**Comment by pjonesIDBS** [comment]
@bastelfreak Tim, thanks for your help in getting the pypuppetdb updated again. It's good to see the tests all passing now :) These changes will make the puppetboard dashboard compatible with all the latest puppet forge module updates. If you're happy with these changes would we be able to release a new version of puppetboard into the forge?

Thanks,

Phil

**Comment by bastelfreak** [comment]
Hi,
I will try to do a new release later. Thanks for your work.

**Comment by pjonesIDBS** [comment]
@bastelfreak Any news on the new release? How soon do you think something can be pushed into the forge?

**Pull request merged**
