### PR TITLE
Add support for require ldap-group

### PR DESCRIPTION
**Pull request by rendhalver**
Add support for LDAP require group for apache config

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @rendhalver, thanks for the PR. Can you please add spec tests for this?

**Comment by wyardley** [comment]
@rendhalver are you still interested in getting this merged, and if so, are you able to add tests? We can help with how to do that if needed.

**Comment by ekohl** [comment]
This needs a rebase now.

**Comment by rendhalver** [comment]
Sorry gang. I didn't notice these comments till now.
I will get this rebased and try and get spec tests added on the weekend.

**Comment by swenske** [comment]
Hi guys! 

What about the merge ? I need this feature too.

Tahnks

**Comment by wyardley** [comment]
@swenske still has no tests and has merge conflicts

**Comment by swenske** [comment]
Hello @wyardley ,

I created PR #232 which has no merge conflict, but I don't hnow how to add tests.

**Comment by wyardley** [comment]
Closing for #236

**Pull request closed without merging**
