### PR TITLE
allow puppet/python 4.x / use puppet/epel instead of stahnma-epel

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by bastelfreak** [comment]
I restared the one failed travis job

**Comment by pjonesIDBS** [comment]
Pleased to see this is a WIP! 

I've updated my local dev Puppet Master clone of puppet-puppetboard so the metadata permits puppet/python < 5.0.0 and all works nicely.

When do you think a release will be available supporting puppet/python > 4.x?

In terms of the README.md file the section for Python 3.x on RHEL / CentOS 7 it needs some work. The config there didn't work at all an even includes incorrect parameters for the puppetboard class.

Due to issues with the RH software collections versions of apache etc being a pain to manage, it was much easier to install the IUS repo version of python360-mod_wsgi. This works seamlessly with the standard httpd package. Very few changes were required to my existing manifest.

I can create an issue in the project if you're interested in seeing / documenting my config for Apache + Python 3 support.

**Comment by bastelfreak** [comment]
@pjonesIDBS thanks for the comment. because of the failing tests I cannot merge this at the moment. Can you provide a PR that updates the README.md?

**Comment by pjonesIDBS** [comment]
I've created https://github.com/voxpupuli/puppet-puppetboard/pull/285 with some alterantive guidance in the README.md. Apologies for not getting to this sooner.

**Comment by bastelfreak** [comment]
those changes are now in our master branch :)

**Pull request closed without merging**
